### ISSUE TITLE
Go button disabled only in JVM version

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Tortoise#148] opened 2015-06-07 16:29 UTC
The Climate Change model does not disable the Go button before Setup has been run (unlike the JVM version). Clicking the Go button results in the model running but not well (no graph update, default shapes, no tick counter display).

**Comment by TheBizzle** [comment] 2015-06-07 17:32
Duplicate of NetLogo/Galapagos#220

**Closed by TheBizzle** 2015-06-07 17:32 UTC
Labels: duplicate
