### ISSUE TITLE
create-temporary-plot-pen creates pens even if pen exists

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/Tortoise#141] opened 2015-05-19 15:46 UTC
Documentation says "If a pen with that name already exists in the current plot, no new pen is created, and the existing pen is set to the current pen."

Using http://li425-91.members.linode.com:9000/
on
http://734.m4a-gae-hrd.appspot.com/p/5fHpt0A3iLeSK0uT5E1G49.nlogo

So new additional pens are created on each tick.

**Comment by TheBizzle** [comment] 2015-05-19 17:12
Thanks for the report, @ToonTalk.  Good catch!

The good news: The problem is pretty simple, and I've already produced a fix for this that I'm pretty confident in with 986d655d4b122683c272674317d34e03ddea0787.

The bad news: Recent changes to the parser have broken your model in another way, so, even if I pushed my fix right now, your model still won't work until the parser fixes have been made.  See NetLogo/NetLogo-Headless#44.  Hopefully we can get all that resolved shortly.

**Closed** 2015-05-19 22:00 UTC
Labels: bug
